version: '3.4'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - webtrees
    restart: on-failure

  webtrees:
    build: webtrees
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    image: mariadb:10.2
    restart: on-failure
