version: '3.4'
services:
  nginx:
    ports:
      - '80:80'
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d:ro
      - webtrees:/var/www/html:ro

  webtrees:
    volumes:
      - webtrees:/var/www/html

  mariadb:
    volumes:
      - ${PWD}/database:/var/lib/mysql

volumes:
  webtrees:
