version: '3.4'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - webtrees
    restart: on-failure

  webtrees:
    build: webtrees
    depends_on:
      - mariadb
    restart: on-failure

  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-webtrees}
      MYSQL_USER: ${MYSQL_USER:-webtrees}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    restart: on-failure
