version: '3.4'
services:
  nginx:
    image: nginx:latest
    restart: on-failure
    depends_on:
      - mariadb

  webtrees:
    build: webtrees
    restart: on-failure
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.2
    restart: on-failure
